[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault_2 = "qM3Smne6PvVzc7JbWvHPyKa4cZj2YdEZB694dAGDcgp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lalo/Q3_2025_Builder_EduardoRamirez/Turbin3-wallet.json" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
