[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_staking = "61z328xZYQ4ou2M22KEY8r9GHJja6bcg8oDor627SGXz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lalo/Q3_2025_Builder_EduardoRamirez/Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
