[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
escrow = "4JZUud5jkp1diBpkVqE1N7Ra62UEmyHYUhFqgbuT5bBZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lalo/Q3_2025_Builder_EduardoRamirez/escrow/Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
